version: '3.8'

services:
  sast-people:
    build:
      context: .
      dockerfile: Dockerfile
    image: sast/sast-people
    container_name: sast-people
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - NONCESTR=${NONCESTR}
      - LINK_CLIENT_ID=${LINK_CLIENT_ID}
      - LINK_CLIENT_SECRET=${LINK_CLIENT_SECRET}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

networks:
  sast-network:
    driver: bridge
