import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Input } from "@/components/ui/input";
import {
	Package2,
	Bell,
	ShoppingCart,
	Badge,
	Package,
	Users,
	LineChart,
	Menu,
	Search,
	CircleUser,
	Home as HomeIcon,
	TicketsPlane,
	UserPen,
	Workflow,
	FilePenLine,
	SquareChartGantt,
} from "lucide-react";
import {
	Card,
	CardHeader,
	CardTitle,
	CardDescription,
	CardContent,
} from "@/components/ui/card";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Header, PageTitle } from "@/components/route";
import { FeishuSDKInject } from "@/components/feishuInject";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="zh-cn">
			<body className={inter.className}>
				<div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
					<div className="hidden border-r bg-muted/40 md:block">
						<div className="flex h-full max-h-screen flex-col gap-2">
							<div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
								<Link
									href="/"
									className="flex items-center gap-2 font-semibold"
								>
									<TicketsPlane className="h-6 w-6" />
									<span className="">SAST 招新</span>
								</Link>
							</div>
							<Header type={"pc"} />
							<div className="mt-auto p-4">
								<Card x-chunk="dashboard-02-chunk-0">
									<CardHeader className="p-2 pt-0 md:p-4">
										<CardTitle>Maxtune</CardTitle>
										<CardDescription>讲师</CardDescription>
									</CardHeader>
									<CardContent>
										<Button
											size="sm"
											className="w-full"
											variant="outline"
										>
											退出登录
										</Button>
									</CardContent>
								</Card>
							</div>
						</div>
					</div>
					<div className="flex flex-col">
						<header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:hidden md:hidden">
							<Header type={"mobile"} />
						</header>
						<main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
							{children}
						</main>
					</div>
				</div>
				<FeishuSDKInject />
			</body>
		</html>
	);
}
